export type LabTest = {
  id: string;
  name: string;
  description: string;
  price: number;
  mrp: number;
  discount: number;
  reportTime: string;
  sampleType: string;
  category: string;
  testsIncluded: string[];
  homeCollection: boolean;
  popular: boolean;
  emoji: string;
};

export const LAB_TEST_CATEGORIES = [
  "All",
  "Full Body",
  "Blood Tests",
  "Thyroid",
  "Diabetes",
  "Heart",
  "Liver & Kidney",
  "Women's Health",
];

export const LAB_TESTS: LabTest[] = [
  {
    id: "lt1",
    name: "Full Body Checkup",
    description: "Comprehensive health screening covering all major organ systems and key health markers.",
    price: 999,
    mrp: 2499,
    discount: 60,
    reportTime: "24 hours",
    sampleType: "Blood + Urine",
    category: "Full Body",
    testsIncluded: ["CBC", "Blood Sugar", "Lipid Profile", "Liver Function", "Kidney Function", "Thyroid (T3, T4, TSH)", "Urine Routine"],
    homeCollection: true,
    popular: true,
    emoji: "🔬",
  },
  {
    id: "lt2",
    name: "Complete Blood Count (CBC)",
    description: "Measures all components of blood — red cells, white cells, platelets, and haemoglobin.",
    price: 199,
    mrp: 350,
    discount: 43,
    reportTime: "6 hours",
    sampleType: "Blood",
    category: "Blood Tests",
    testsIncluded: ["Haemoglobin", "RBC", "WBC", "Platelets", "Haematocrit", "MCV", "MCH"],
    homeCollection: true,
    popular: true,
    emoji: "🩸",
  },
  {
    id: "lt3",
    name: "Thyroid Profile (T3, T4, TSH)",
    description: "Detects thyroid disorders including hypothyroidism and hyperthyroidism.",
    price: 349,
    mrp: 699,
    discount: 50,
    reportTime: "12 hours",
    sampleType: "Blood",
    category: "Thyroid",
    testsIncluded: ["T3 (Triiodothyronine)", "T4 (Thyroxine)", "TSH (Thyroid Stimulating Hormone)"],
    homeCollection: true,
    popular: true,
    emoji: "🦋",
  },
  {
    id: "lt4",
    name: "HbA1c (Diabetes Check)",
    description: "Measures average blood sugar over the past 2–3 months. Key test for diabetes management.",
    price: 299,
    mrp: 499,
    discount: 40,
    reportTime: "8 hours",
    sampleType: "Blood",
    category: "Diabetes",
    testsIncluded: ["HbA1c", "Fasting Blood Glucose", "Post Prandial Glucose"],
    homeCollection: true,
    popular: true,
    emoji: "📊",
  },
  {
    id: "lt5",
    name: "Lipid Profile",
    description: "Evaluates cholesterol levels and cardiovascular risk assessment.",
    price: 249,
    mrp: 499,
    discount: 50,
    reportTime: "8 hours",
    sampleType: "Blood (Fasting)",
    category: "Heart",
    testsIncluded: ["Total Cholesterol", "LDL", "HDL", "Triglycerides", "VLDL", "LDL/HDL Ratio"],
    homeCollection: true,
    popular: false,
    emoji: "❤️",
  },
  {
    id: "lt6",
    name: "Liver Function Test (LFT)",
    description: "Assesses liver health and detects conditions like jaundice, hepatitis, or cirrhosis.",
    price: 399,
    mrp: 749,
    discount: 47,
    reportTime: "12 hours",
    sampleType: "Blood",
    category: "Liver & Kidney",
    testsIncluded: ["SGOT", "SGPT", "Alkaline Phosphatase", "Bilirubin (Total & Direct)", "Albumin", "Total Protein"],
    homeCollection: true,
    popular: false,
    emoji: "🫀",
  },
  {
    id: "lt7",
    name: "Kidney Function Test (KFT)",
    description: "Evaluates kidney performance through key markers like creatinine and urea.",
    price: 349,
    mrp: 649,
    discount: 46,
    reportTime: "12 hours",
    sampleType: "Blood + Urine",
    category: "Liver & Kidney",
    testsIncluded: ["Serum Creatinine", "Blood Urea", "Uric Acid", "Urine Routine & Microscopy", "eGFR"],
    homeCollection: true,
    popular: false,
    emoji: "🫘",
  },
  {
    id: "lt8",
    name: "Vitamin D & B12 Panel",
    description: "Checks for deficiencies in essential vitamins that affect bone, nerve, and energy health.",
    price: 599,
    mrp: 1199,
    discount: 50,
    reportTime: "24 hours",
    sampleType: "Blood",
    category: "Blood Tests",
    testsIncluded: ["Vitamin D (25-OH)", "Vitamin B12", "Calcium", "Phosphorus"],
    homeCollection: true,
    popular: true,
    emoji: "☀️",
  },
  {
    id: "lt9",
    name: "Women's Hormonal Panel",
    description: "Comprehensive hormonal assessment for women — fertility, PCOS, menopause screening.",
    price: 799,
    mrp: 1599,
    discount: 50,
    reportTime: "24 hours",
    sampleType: "Blood",
    category: "Women's Health",
    testsIncluded: ["FSH", "LH", "Estrogen", "Progesterone", "Prolactin", "AMH", "Testosterone"],
    homeCollection: true,
    popular: false,
    emoji: "🌸",
  },
  {
    id: "lt10",
    name: "Cardiac Risk Profile",
    description: "Advanced heart risk assessment including troponin, CRP, and homocysteine.",
    price: 1199,
    mrp: 2499,
    discount: 52,
    reportTime: "24 hours",
    sampleType: "Blood",
    category: "Heart",
    testsIncluded: ["Troponin I", "hs-CRP", "Homocysteine", "Lipid Profile", "BNP", "Fibrinogen"],
    homeCollection: true,
    popular: false,
    emoji: "💓",
  },
  {
    id: "lt11",
    name: "COVID-19 RT-PCR",
    description: "Gold standard test for COVID-19 detection using PCR technology.",
    price: 349,
    mrp: 500,
    discount: 30,
    reportTime: "6–8 hours",
    sampleType: "Nasal/Throat Swab",
    category: "Blood Tests",
    testsIncluded: ["SARS-CoV-2 RNA Detection"],
    homeCollection: true,
    popular: false,
    emoji: "🦠",
  },
  {
    id: "lt12",
    name: "Diabetes Management Panel",
    description: "Complete diabetes monitoring with sugar levels, kidney function, and cholesterol.",
    price: 699,
    mrp: 1499,
    discount: 53,
    reportTime: "24 hours",
    sampleType: "Blood + Urine",
    category: "Diabetes",
    testsIncluded: ["HbA1c", "Fasting Glucose", "Post-Prandial Glucose", "Insulin Fasting", "Lipid Profile", "Microalbumin Urine"],
    homeCollection: true,
    popular: true,
    emoji: "📉",
  },
];

export const TIME_SLOTS_LAB = [
  "06:00 AM – 08:00 AM",
  "08:00 AM – 10:00 AM",
  "10:00 AM – 12:00 PM",
  "12:00 PM – 02:00 PM",
  "02:00 PM – 04:00 PM",
  "04:00 PM – 06:00 PM",
];
