export type Medicine = {
  id: string;
  name: string;
  salt: string;
  category: string;
  price: number;
  mrp: number;
  discount: number;
  manufacturer: string;
  availability: "In Stock" | "Limited Stock" | "Out of Stock";
  requiresPrescription: boolean;
  dosage: string;
  imageEmoji: string;
  image?: string;
};

export const MEDICINE_CATEGORIES = [
  "All",
  "Pain Relief",
  "Vitamins & Supplements",
  "Antibiotics",
  "Diabetes",
  "Heart & BP",
  "Digestive Health",
  "Cold & Fever",
  "Skin Care",
];

export const MEDICINES: Medicine[] = [
  {
    id: "m1",
    name: "Crocin 500mg",
    salt: "Paracetamol",
    category: "Pain Relief",
    price: 28,
    mrp: 35,
    discount: 20,
    manufacturer: "GSK",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "500mg, 15 Tablets",
    imageEmoji: "💊",
    image: "/images/medicines/crocin.png",
  },
  {
    id: "m2",
    name: "Dolo 650",
    salt: "Paracetamol",
    category: "Cold & Fever",
    price: 30,
    mrp: 38,
    discount: 21,
    manufacturer: "Micro Labs",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "650mg, 15 Tablets",
    imageEmoji: "💊",
    image: "/images/medicines/dolo.png",
  },
  {
    id: "m3",
    name: "Azithral 500",
    salt: "Azithromycin",
    category: "Antibiotics",
    price: 72,
    mrp: 95,
    discount: 24,
    manufacturer: "Alembic",
    availability: "In Stock",
    requiresPrescription: true,
    dosage: "500mg, 5 Tablets",
    imageEmoji: "🔬",
    image: "/images/medicines/azithral.png",
  },
  {
    id: "m4",
    name: "Metformin 500",
    salt: "Metformin HCl",
    category: "Diabetes",
    price: 45,
    mrp: 60,
    discount: 25,
    manufacturer: "Sun Pharma",
    availability: "In Stock",
    requiresPrescription: true,
    dosage: "500mg, 10 Tablets",
    imageEmoji: "🩺",
    image: "/images/medicines/metformin.png",
  },
  {
    id: "m5",
    name: "Vitamin D3 60K",
    salt: "Cholecalciferol",
    category: "Vitamins & Supplements",
    price: 120,
    mrp: 160,
    discount: 25,
    manufacturer: "Abbott",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "60,000 IU, 4 Capsules",
    imageEmoji: "☀️",
    image: "/images/medicines/vitamin_d3.png",
  },
  {
    id: "m6",
    name: "Omega 3 Fish Oil",
    salt: "Omega-3 Fatty Acids",
    category: "Vitamins & Supplements",
    price: 249,
    mrp: 320,
    discount: 22,
    manufacturer: "HealthKart",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "1000mg, 60 Softgels",
    imageEmoji: "🐟",
    image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m7",
    name: "Telmisartan 40",
    salt: "Telmisartan",
    category: "Heart & BP",
    price: 88,
    mrp: 115,
    discount: 23,
    manufacturer: "Cipla",
    availability: "In Stock",
    requiresPrescription: true,
    dosage: "40mg, 10 Tablets",
    imageEmoji: "❤️",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m8",
    name: "Pantop 40",
    salt: "Pantoprazole",
    category: "Digestive Health",
    price: 65,
    mrp: 85,
    discount: 24,
    manufacturer: "Aristo",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "40mg, 15 Tablets",
    imageEmoji: "🟡",
    image: "https://images.unsplash.com/photo-1550572017-edb774b7c6cb?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m9",
    name: "Allegra 120",
    salt: "Fexofenadine",
    category: "Cold & Fever",
    price: 98,
    mrp: 130,
    discount: 25,
    manufacturer: "Sanofi",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "120mg, 10 Tablets",
    imageEmoji: "🌸",
    image: "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m10",
    name: "Betadine Ointment",
    salt: "Povidone Iodine",
    category: "Skin Care",
    price: 78,
    mrp: 99,
    discount: 21,
    manufacturer: "Win-Medicare",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "20g Ointment",
    imageEmoji: "🧴",
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m11",
    name: "Combiflam",
    salt: "Ibuprofen + Paracetamol",
    category: "Pain Relief",
    price: 40,
    mrp: 52,
    discount: 23,
    manufacturer: "Sanofi",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "400mg+325mg, 20 Tablets",
    imageEmoji: "💊",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m12",
    name: "Glucon-D",
    salt: "Dextrose Monohydrate",
    category: "Vitamins & Supplements",
    price: 85,
    mrp: 99,
    discount: 14,
    manufacturer: "Heinz",
    availability: "Limited Stock",
    requiresPrescription: false,
    dosage: "500g Powder",
    imageEmoji: "🍊",
    image: "https://images.unsplash.com/photo-1559415053-ec8d7a12cc93?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m13",
    name: "Augmentin 625",
    salt: "Amoxicillin + Clavulanate",
    category: "Antibiotics",
    price: 195,
    mrp: 248,
    discount: 21,
    manufacturer: "GSK",
    availability: "In Stock",
    requiresPrescription: true,
    dosage: "625mg, 10 Tablets",
    imageEmoji: "🔬",
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m14",
    name: "Glycomet GP1",
    salt: "Glimepiride + Metformin",
    category: "Diabetes",
    price: 98,
    mrp: 130,
    discount: 25,
    manufacturer: "USV",
    availability: "In Stock",
    requiresPrescription: true,
    dosage: "1mg+500mg, 15 Tablets",
    imageEmoji: "🩺",
    image: "https://images.unsplash.com/photo-1583324113626-70df0f4deaab?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m15",
    name: "Atorvastatin 10",
    salt: "Atorvastatin",
    category: "Heart & BP",
    price: 55,
    mrp: 72,
    discount: 24,
    manufacturer: "Cipla",
    availability: "In Stock",
    requiresPrescription: true,
    dosage: "10mg, 10 Tablets",
    imageEmoji: "❤️",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m16",
    name: "Mucaine Gel",
    salt: "Oxethazaine + Antacid",
    category: "Digestive Health",
    price: 68,
    mrp: 88,
    discount: 23,
    manufacturer: "Pfizer",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "170ml Suspension",
    imageEmoji: "🟢",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m17",
    name: "Moov Cream",
    salt: "Nimesulide (topical)",
    category: "Pain Relief",
    price: 125,
    mrp: 150,
    discount: 17,
    manufacturer: "Reckitt",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "50g Cream",
    imageEmoji: "🧴",
    image: "https://images.unsplash.com/photo-1556228578-8d89b6a43588?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m18",
    name: "Cetrizine 10mg",
    salt: "Cetirizine HCl",
    category: "Cold & Fever",
    price: 18,
    mrp: 24,
    discount: 25,
    manufacturer: "Cipla",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "10mg, 10 Tablets",
    imageEmoji: "🌿",
    image: "https://images.unsplash.com/photo-1628771065518-0d82f1938462?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m19",
    name: "B-Complex with C",
    salt: "Vitamins B1, B2, B6, B12, C",
    category: "Vitamins & Supplements",
    price: 89,
    mrp: 115,
    discount: 23,
    manufacturer: "Pfizer",
    availability: "In Stock",
    requiresPrescription: false,
    dosage: "30 Tablets",
    imageEmoji: "🌟",
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m20",
    name: "Calamine Lotion",
    salt: "Calamine + Zinc Oxide",
    category: "Skin Care",
    price: 55,
    mrp: 72,
    discount: 24,
    manufacturer: "Lacto Calamine",
    availability: "Limited Stock",
    requiresPrescription: false,
    dosage: "120ml Lotion",
    imageEmoji: "🌸",
    image: "https://images.unsplash.com/photo-1556228720-1c2a033c46b5?q=80&w=400&auto=format&fit=crop",
  },
];
